### ISSUE TITLE
没有数据库文件

### ISSUE THREAD

**Issue by SGL647** [ADKcodeXD/ADKblog-backend#2]
没有数据库文件
![捕获](https://user-images.githubusercontent.com/61075731/173559857-3ec8cf9b-7794-4e94-8589-ade4d2b5532f.PNG)

**Comment by ADKcodeXD** [comment]
放到仓库中了~
可以自己进行配置
https://github.com/ADKcodeXD/ADKblog-backend/tree/main/sql
